server:
  port: 80
github:
  client:
    id: 3a7029f3685d6900456c
    secret: 7232968440ed829865c1983eb5706c57ebc1bf4b
  redirect:
      uri: http://localhost:80/callback
spring:
  thymeleaf:
    cache: false
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: admin
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.community2.model
  mapper-locations: classpath:/mapper/*.xml

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
